fix miss _client bug when login with authToken
use authToken won't call login(), therefore _client won't be defined.

>>> client = LineClient(authToken="DJPoUwXLipVk7ZgY638eOX6qrNVAgxIsOLWld22mY=")
<line.client.LineClient object at 0x106dc2410>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "line/client.py", line 81, in __init__
    self.revision = self._getLastOpRevision()
  File "line/api.py", line 233, in _getLastOpRevision
    return self._client.getLastOpRevision()
AttributeError: 'LineClient' object has no attribute '_client'